backend:
  name: git-gateway
  branch: main
  accept_roles:
    - admin

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'ブログ記事'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '公開日', name: 'date', widget: 'datetime' }
      - { label: 'サムネイル', name: 'thumbnail', widget: 'image', default: "noimage.png" }
      - { label: "タグ", name: "tags", widget: "list"}
      - { label: '概要', name: 'description', widget: 'string' }
      - { label: '本文', name: 'body', widget: 'markdown' }