backend:
  name: git-gateway
  branch: main
  use_large_media_transforms_in_media_library: false 
  accept_roles:
    - admin

media_folder: static/img/post
public_folder: /img/post

publish_mode: editorial_workflow

collections:
  - name: 'blog'
    label: 'ブログ記事'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '公開日', name: 'date', widget: 'datetime' }
      - { label: "タグ", name: "tags", widget: "list"}
      - { label: "限定公開", name: "isOpen", widget: "boolean", default: "false"}
      - { label: '概要', name: 'description', widget: 'string' }
      - { label: '本文', name: 'body', widget: 'markdown' }